export interface KitItem {
  sku: string;
  name: string;
  category: KitCategory;
  essential: boolean;
  priceEur: number;
  weightKg: number;
  amazonUrl?: string;
  decathlonUrl?: string;
  tags: string[];
  minPersons?: number;
  forChildren?: boolean;
  forPets?: boolean;
  forMedical?: boolean;
}

export type KitCategory =
  | "water"
  | "food"
  | "light"
  | "communication"
  | "health"
  | "documents"
  | "tools"
  | "shelter"
  | "hygiene"
  | "cash"
  | "kids"
  | "pets";

export const CATEGORY_LABELS: Record<KitCategory, string> = {
  water: "Eau & Hydratation",
  food: "Alimentation",
  light: "Éclairage",
  communication: "Communication",
  health: "Santé & Premiers soins",
  documents: "Documents",
  tools: "Outils",
  shelter: "Abri & Chaleur",
  hygiene: "Hygiène",
  cash: "Liquidités",
  kids: "Enfants",
  pets: "Animaux",
};

export const KIT_CATALOG: KitItem[] = [
  // ─── EAU ─────────────────────────────────────────────────────
  {
    sku: "WTR-001",
    name: "Eau minérale 1,5L (x6)",
    category: "water",
    essential: true,
    priceEur: 4.5,
    weightKg: 9.0,
    amazonUrl: "https://www.amazon.com.be/dp/B07PZ4CKRX?tag=survikit-21",
    tags: ["urban", "family", "mountain", "forest"],
  },
  {
    sku: "WTR-002",
    name: "Pastilles de purification d'eau (100 pcs)",
    category: "water",
    essential: true,
    priceEur: 12.9,
    weightKg: 0.05,
    amazonUrl: "https://www.amazon.com.be/dp/B001949TUQ?tag=survikit-21",
    tags: ["urban", "family", "mountain", "forest", "evacuation"],
  },
  {
    sku: "WTR-003",
    name: "Filtre à eau portable LifeStraw",
    category: "water",
    essential: false,
    priceEur: 24.9,
    weightKg: 0.056,
    amazonUrl: "https://www.amazon.com.be/dp/B006QF3TW4?tag=survikit-21",
    tags: ["mountain", "forest"],
  },
  {
    sku: "WTR-004",
    name: "Gourde 1L isotherme",
    category: "water",
    essential: true,
    priceEur: 18.9,
    weightKg: 0.28,
    decathlonUrl: "https://www.decathlon.be/fr/p/gourde-isotherme-1l/_/R-p-325971",
    tags: ["mountain", "forest", "evacuation"],
  },
  {
    sku: "WTR-005",
    name: "Sac de stockage eau pliable 10L",
    category: "water",
    essential: false,
    priceEur: 8.9,
    weightKg: 0.12,
    amazonUrl: "https://www.amazon.com.be/dp/B07H8XS3W3?tag=survikit-21",
    tags: ["urban", "family"],
  },

  // ─── NOURRITURE ───────────────────────────────────────────────
  {
    sku: "FD-001",
    name: "Barres énergétiques 2400 kcal (boîte 9 barres)",
    category: "food",
    essential: true,
    priceEur: 16.9,
    weightKg: 0.43,
    amazonUrl: "https://www.amazon.com.be/dp/B000FDHU2A?tag=survikit-21",
    tags: ["urban", "evacuation", "mountain"],
  },
  {
    sku: "FD-002",
    name: "Repas lyophilisé montagne (x4)",
    category: "food",
    essential: false,
    priceEur: 32.0,
    weightKg: 0.52,
    decathlonUrl: "https://www.decathlon.be/fr/p/repas-lyophilise/_/R-p-169979",
    tags: ["mountain", "forest"],
  },
  {
    sku: "FD-003",
    name: "Conserves légumes / protéines (x6)",
    category: "food",
    essential: true,
    priceEur: 12.0,
    weightKg: 1.8,
    tags: ["urban", "family"],
  },
  {
    sku: "FD-004",
    name: "Crackers sans gluten (x3 paquets)",
    category: "food",
    essential: true,
    priceEur: 7.5,
    weightKg: 0.36,
    tags: ["family", "urban"],
  },
  {
    sku: "FD-005",
    name: "Noix & fruits secs assortis 500g",
    category: "food",
    essential: true,
    priceEur: 9.9,
    weightKg: 0.5,
    amazonUrl: "https://www.amazon.com.be/dp/B07D7DRMTF?tag=survikit-21",
    tags: ["urban", "family", "mountain", "evacuation", "forest"],
  },
  {
    sku: "FD-006",
    name: "Réchaud à gaz compact + 2 cartouches",
    category: "food",
    essential: false,
    priceEur: 29.9,
    weightKg: 0.38,
    decathlonUrl: "https://www.decathlon.be/fr/p/rechaud-a-gaz/_/R-p-325698",
    tags: ["mountain", "forest", "family"],
  },
  {
    sku: "FD-007",
    name: "Lait maternisé / alimentation bébé (x4 doses)",
    category: "food",
    essential: true,
    priceEur: 14.9,
    weightKg: 0.4,
    forChildren: true,
    tags: ["family"],
  },
  {
    sku: "FD-008",
    name: "Snacks enfants sans additifs (x10)",
    category: "food",
    essential: true,
    priceEur: 8.9,
    weightKg: 0.3,
    forChildren: true,
    tags: ["family"],
  },

  // ─── ÉCLAIRAGE ────────────────────────────────────────────────
  {
    sku: "LT-001",
    name: "Lampe frontale LED rechargeable 350 lm",
    category: "light",
    essential: true,
    priceEur: 24.9,
    weightKg: 0.09,
    decathlonUrl: "https://www.decathlon.be/fr/p/lampe-frontale-led/_/R-p-325973",
    tags: ["urban", "family", "mountain", "forest", "evacuation"],
  },
  {
    sku: "LT-002",
    name: "Piles AAA rechargeables (x8) + chargeur",
    category: "light",
    essential: true,
    priceEur: 18.9,
    weightKg: 0.22,
    amazonUrl: "https://www.amazon.com.be/dp/B00HZV9WTM?tag=survikit-21",
    tags: ["urban", "family"],
  },
  {
    sku: "LT-003",
    name: "Batterie solaire externe 20 000 mAh",
    category: "light",
    essential: false,
    priceEur: 39.9,
    weightKg: 0.42,
    amazonUrl: "https://www.amazon.com.be/dp/B07MMWH5LV?tag=survikit-21",
    tags: ["urban", "family", "mountain"],
  },
  {
    sku: "LT-004",
    name: "Bougies de survie longue durée (x10, 9h chacune)",
    category: "light",
    essential: true,
    priceEur: 8.9,
    weightKg: 0.35,
    amazonUrl: "https://www.amazon.com.be/dp/B00FQAKNHI?tag=survikit-21",
    tags: ["urban", "family"],
  },
  {
    sku: "LT-005",
    name: "Lampe tempête à huile",
    category: "light",
    essential: false,
    priceEur: 19.9,
    weightKg: 0.48,
    tags: ["family", "urban"],
  },

  // ─── COMMUNICATION ────────────────────────────────────────────
  {
    sku: "COM-001",
    name: "Radio portable AM/FM à manivelle + batterie solaire",
    category: "communication",
    essential: true,
    priceEur: 34.9,
    weightKg: 0.32,
    amazonUrl: "https://www.amazon.com.be/dp/B083G1QKRB?tag=survikit-21",
    tags: ["urban", "family", "mountain", "evacuation"],
  },
  {
    sku: "COM-002",
    name: "Sifflet de signalisation haute fréquence",
    category: "communication",
    essential: true,
    priceEur: 4.9,
    weightKg: 0.02,
    decathlonUrl: "https://www.decathlon.be/fr/p/sifflet-de-securite/_/R-p-145003",
    tags: ["mountain", "forest", "evacuation", "urban"],
  },
  {
    sku: "COM-003",
    name: "Miroir de signalisation",
    category: "communication",
    essential: false,
    priceEur: 7.9,
    weightKg: 0.04,
    tags: ["mountain", "forest"],
  },
  {
    sku: "COM-004",
    name: "Talkie-walkie longue portée (paire, 10 km)",
    category: "communication",
    essential: false,
    priceEur: 49.9,
    weightKg: 0.36,
    amazonUrl: "https://www.amazon.com.be/dp/B01GJQBX5E?tag=survikit-21",
    tags: ["family", "mountain"],
  },

  // ─── SANTÉ ────────────────────────────────────────────────────
  {
    sku: "HLT-001",
    name: "Trousse de premiers secours complète (24 pièces)",
    category: "health",
    essential: true,
    priceEur: 22.9,
    weightKg: 0.35,
    amazonUrl: "https://www.amazon.com.be/dp/B00KIQS9ZA?tag=survikit-21",
    tags: ["urban", "family", "mountain", "forest", "evacuation"],
  },
  {
    sku: "HLT-002",
    name: "Couverture de survie isotherme (x2)",
    category: "health",
    essential: true,
    priceEur: 6.9,
    weightKg: 0.08,
    decathlonUrl: "https://www.decathlon.be/fr/p/couverture-de-survie/_/R-p-50765",
    tags: ["urban", "family", "mountain", "forest", "evacuation"],
  },
  {
    sku: "HLT-003",
    name: "Paracétamol 500mg (boîte 30 cp)",
    category: "health",
    essential: true,
    priceEur: 3.9,
    weightKg: 0.06,
    tags: ["urban", "family"],
  },
  {
    sku: "HLT-004",
    name: "Paracétamol pédiatrique 250mg (boîte 20 cp)",
    category: "health",
    essential: true,
    priceEur: 5.9,
    weightKg: 0.05,
    forChildren: true,
    tags: ["family"],
  },
  {
    sku: "HLT-005",
    name: "Pastilles iode (ordonnance non requise, adultes)",
    category: "health",
    essential: false,
    priceEur: 7.9,
    weightKg: 0.03,
    tags: ["urban", "family"],
  },
  {
    sku: "HLT-006",
    name: "Masques FFP2 (x10)",
    category: "health",
    essential: true,
    priceEur: 9.9,
    weightKg: 0.08,
    amazonUrl: "https://www.amazon.com.be/dp/B08MRS7GRP?tag=survikit-21",
    tags: ["urban", "family", "evacuation"],
  },
  {
    sku: "HLT-007",
    name: "Gel hydroalcoolique 500ml",
    category: "health",
    essential: true,
    priceEur: 4.9,
    weightKg: 0.52,
    tags: ["urban", "family"],
  },
  {
    sku: "HLT-008",
    name: "Pansements hemostatics (x5)",
    category: "health",
    essential: false,
    priceEur: 14.9,
    weightKg: 0.12,
    amazonUrl: "https://www.amazon.com.be/dp/B08XZ3B2VP?tag=survikit-21",
    tags: ["mountain", "forest"],
  },

  // ─── DOCUMENTS ────────────────────────────────────────────────
  {
    sku: "DOC-001",
    name: "Pochette étanche documents A4",
    category: "documents",
    essential: true,
    priceEur: 8.9,
    weightKg: 0.04,
    amazonUrl: "https://www.amazon.com.be/dp/B07KQD8S7M?tag=survikit-21",
    tags: ["urban", "family", "evacuation"],
  },
  {
    sku: "DOC-002",
    name: "Carnet étanche + stylo bille tout-temps",
    category: "documents",
    essential: true,
    priceEur: 12.9,
    weightKg: 0.09,
    tags: ["urban", "family", "mountain", "forest", "evacuation"],
  },

  // ─── OUTILS ───────────────────────────────────────────────────
  {
    sku: "TL-001",
    name: "Couteau multifonctions Victorinox Tinker",
    category: "tools",
    essential: true,
    priceEur: 29.9,
    weightKg: 0.07,
    amazonUrl: "https://www.amazon.com.be/dp/B00004YVB4?tag=survikit-21",
    tags: ["urban", "family", "mountain", "forest", "evacuation"],
  },
  {
    sku: "TL-002",
    name: "Allume-feu Firesteel + grattoir",
    category: "tools",
    essential: true,
    priceEur: 11.9,
    weightKg: 0.04,
    decathlonUrl: "https://www.decathlon.be/fr/p/allume-feu-silex/_/R-p-338037",
    tags: ["mountain", "forest"],
  },
  {
    sku: "TL-003",
    name: "Briquet tempête imperméable",
    category: "tools",
    essential: true,
    priceEur: 9.9,
    weightKg: 0.06,
    amazonUrl: "https://www.amazon.com.be/dp/B07KH8FVVP?tag=survikit-21",
    tags: ["urban", "family", "mountain", "forest"],
  },
  {
    sku: "TL-004",
    name: "Corde de survie paracorde 30m",
    category: "tools",
    essential: false,
    priceEur: 12.9,
    weightKg: 0.21,
    amazonUrl: "https://www.amazon.com.be/dp/B00E78D71S?tag=survikit-21",
    tags: ["mountain", "forest"],
  },
  {
    sku: "TL-005",
    name: "Duct tape 50m",
    category: "tools",
    essential: true,
    priceEur: 5.9,
    weightKg: 0.14,
    tags: ["urban", "family", "mountain", "forest"],
  },
  {
    sku: "TL-006",
    name: "Gants de travail résistants (1 paire)",
    category: "tools",
    essential: true,
    priceEur: 8.9,
    weightKg: 0.08,
    decathlonUrl: "https://www.decathlon.be/fr/p/gants-de-travail/_/R-p-301459",
    tags: ["urban", "family", "mountain", "forest"],
  },
  {
    sku: "TL-007",
    name: "Mini pied-de-biche pliant",
    category: "tools",
    essential: false,
    priceEur: 14.9,
    weightKg: 0.32,
    tags: ["urban", "family"],
  },

  // ─── ABRI & CHALEUR ───────────────────────────────────────────
  {
    sku: "SH-001",
    name: "Sac de couchage léger 0°C compression",
    category: "shelter",
    essential: true,
    priceEur: 49.9,
    weightKg: 0.85,
    decathlonUrl: "https://www.decathlon.be/fr/p/sac-de-couchage-leger/_/R-p-X8488786",
    tags: ["mountain", "forest", "evacuation"],
  },
  {
    sku: "SH-002",
    name: "Tente bivouac 2 places ultralight",
    category: "shelter",
    essential: false,
    priceEur: 89.9,
    weightKg: 1.2,
    decathlonUrl: "https://www.decathlon.be/fr/p/tente-bivouac/_/R-p-X8503765",
    tags: ["forest", "mountain"],
  },
  {
    sku: "SH-003",
    name: "Bâche de survie 3×3m",
    category: "shelter",
    essential: true,
    priceEur: 18.9,
    weightKg: 0.55,
    amazonUrl: "https://www.amazon.com.be/dp/B07DKQWF2F?tag=survikit-21",
    tags: ["forest", "mountain"],
  },
  {
    sku: "SH-004",
    name: "Chaufferettes main (x8, 10h chacune)",
    category: "shelter",
    essential: true,
    priceEur: 11.9,
    weightKg: 0.22,
    tags: ["mountain", "urban", "family"],
  },

  // ─── HYGIÈNE ──────────────────────────────────────────────────
  {
    sku: "HYG-001",
    name: "Kit hygiène compact : brosse/dentifrice/savon",
    category: "hygiene",
    essential: true,
    priceEur: 9.9,
    weightKg: 0.18,
    tags: ["urban", "family", "evacuation"],
  },
  {
    sku: "HYG-002",
    name: "Lingettes désinfectantes (boîte 80)",
    category: "hygiene",
    essential: true,
    priceEur: 6.9,
    weightKg: 0.24,
    tags: ["urban", "family", "evacuation"],
  },
  {
    sku: "HYG-003",
    name: "Papier toilette compact (x4 rouleaux)",
    category: "hygiene",
    essential: true,
    priceEur: 4.9,
    weightKg: 0.24,
    tags: ["urban", "family"],
  },
  {
    sku: "HYG-004",
    name: "Pelle pliant + sacs biodégradables",
    category: "hygiene",
    essential: false,
    priceEur: 12.9,
    weightKg: 0.22,
    tags: ["mountain", "forest"],
  },

  // ─── CASH ─────────────────────────────────────────────────────
  {
    sku: "CSH-001",
    name: "Enveloppe sécurisée pour liquidités (rappel)",
    category: "cash",
    essential: true,
    priceEur: 0,
    weightKg: 0.01,
    tags: ["urban", "family", "evacuation"],
  },

  // ─── ENFANTS ──────────────────────────────────────────────────
  {
    sku: "KDS-001",
    name: "Doudou de secours (1 peluche compressible)",
    category: "kids",
    essential: true,
    priceEur: 12.9,
    weightKg: 0.08,
    forChildren: true,
    tags: ["family"],
  },
  {
    sku: "KDS-002",
    name: "Cartes de jeux imperméables",
    category: "kids",
    essential: false,
    priceEur: 9.9,
    weightKg: 0.06,
    forChildren: true,
    tags: ["family"],
  },
  {
    sku: "KDS-003",
    name: "Sac à dos enfant 10L",
    category: "kids",
    essential: true,
    priceEur: 19.9,
    weightKg: 0.22,
    forChildren: true,
    decathlonUrl: "https://www.decathlon.be/fr/p/sac-a-dos-enfant-10l/_/R-p-325910",
    tags: ["family", "evacuation"],
  },

  // ─── ANIMAUX ──────────────────────────────────────────────────
  {
    sku: "PET-001",
    name: "Croquettes lyophilisées chien/chat 3 jours",
    category: "pets",
    essential: true,
    priceEur: 22.9,
    weightKg: 0.45,
    forPets: true,
    amazonUrl: "https://www.amazon.com.be/dp/B07XJWSSGR?tag=survikit-21",
    tags: ["urban", "family"],
  },
  {
    sku: "PET-002",
    name: "Gamelle pliable + gourde 500ml pour animaux",
    category: "pets",
    essential: true,
    priceEur: 14.9,
    weightKg: 0.18,
    forPets: true,
    tags: ["urban", "family", "evacuation"],
  },
  {
    sku: "PET-003",
    name: "Trousse vétérinaire de base",
    category: "pets",
    essential: false,
    priceEur: 18.9,
    weightKg: 0.22,
    forPets: true,
    tags: ["family", "urban"],
  },
];
